INSERT INTO pricedetails VALUES(1,100,150,10);

INSERT INTO item VALUES(1,"BOOK","THIS IS BOOK",1);


INSERT INTO orders VALUES(1,"SHAFI","RAM","O1","F1",1,"CREATED","BOPIS","NOTE");

INSERT INTO orderalerts VALUES(1,"SHAFI","RAM","HELLO","HELLO ALERT",TRUE,TRUE,1);

INSERT INTO orderevents VALUES(1,"SHAFI","RAM","HI","HI EVENT",1);

INSERT INTO orderline VALUES(1,"SHAFI","RAM",1,1,"CREATED","DTCP","RAIL",1,1,1,1,0,5,"CANCEL TIME STAMP","CANCEL REASON",TRUE,1,1);

INSERT INTO packages VALUES(1,"CREATETIMESTAMP","UPDATEDTIMESTAMP","SHAFI","RAM",1,"P1","SHIPPEDTIMESTAMP","T1","C1","S1","ATTRIBUTE",1);

